language: python

python: "3.6"

git:
  depth: 1

# Install dependencies
install:
  - pip install -r requirements.txt
    
# script to run tests.
script: 
  - python -m unittest test/test.py

after_script:
  - bash <(curl -s https://codecov.io/bash)