# Generated by Django 3.2.7 on 2021-10-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200)),
                ('tag_id', models.CharField(max_length=200)),
            ],
        ),
    ]
