# Generated by Django 3.2.7 on 2021-10-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0002_auto_20211021_1219'),
        ('garnbarn_api', '0002_tag'),
    ]

    operations = [
    ]
