# Generated by Django 3.2.7 on 2021-10-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0003_auto_20211022_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='detail',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
