# Generated by Django 3.2.7 on 2021-10-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0004_auto_20211023_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='detail',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
