# Generated by Django 3.2.7 on 2021-10-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0006_auto_20211023_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
