# Generated by Django 3.2.7 on 2021-10-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0008_alter_tag_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='dueDate'),
        ),
    ]
