# Generated by Django 3.2.7 on 2021-10-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0010_auto_20211024_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
