# Generated by Django 3.2.7 on 2021-10-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0011_tag_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='detail',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
