# Generated by Django 3.2.7 on 2021-10-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0012_auto_20211025_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
