# Generated by Django 3.2.7 on 2021-10-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0013_alter_assignment_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
