# Generated by Django 3.2.7 on 2021-10-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0015_customuser_socialobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='uid',
            field=models.CharField(default='Unknown', max_length=40, primary_key=True, serialize=False),
        ),
    ]
