# Generated by Django 3.2.7 on 2021-10-28 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0016_auto_20211028_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='garnbarn_api.customuser'),
        ),
    ]
