# Generated by Django 3.2.7 on 2021-10-28 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0017_assignment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garnbarn_api.socialobject'),
        ),
    ]
