# Generated by Django 3.2.7 on 2021-10-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0018_alter_customuser_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='reminder_time',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='line',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='SocialObject',
        ),
    ]
