# Generated by Django 3.2.7 on 2021-10-30 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0019_auto_20211031_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='reminder_time',
        ),
    ]
