# Generated by Django 3.2.7 on 2021-10-31 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0021_assignment_reminder_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='owner',
            new_name='author',
        ),
    ]
