# Generated by Django 3.2.7 on 2021-11-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0017_auto_20211031_1630'),
        ('garnbarn_api', '0022_rename_owner_assignment_author'),
    ]

    operations = [
    ]
