# Generated by Django 3.2.7 on 2021-11-01 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0022_rename_owner_assignment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
