# Generated by Django 3.2.7 on 2021-11-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0023_merge_20211101_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='subscriber',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
