# Generated by Django 3.2.7 on 2021-11-01 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0024_tag_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='garnbarn_api.customuser'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='garnbarn_api.customuser'),
        ),
    ]
