# Generated by Django 3.2.7 on 2021-11-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0023_remove_customuser_name'),
        ('garnbarn_api', '0025_auto_20211101_1658'),
    ]

    operations = [
    ]
