# Generated by Django 3.2.7 on 2021-11-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0026_merge_20211102_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uid',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
