# Generated by Django 3.2.7 on 2021-11-03 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0027_alter_customuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='garnbarn_api.customuser'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garnbarn_api.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='garnbarn_api.customuser'),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='tag',
            name='subscriber',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='subscriber', to='garnbarn_api.CustomUser'),
        ),
    ]
