# Generated by Django 3.2.7 on 2021-11-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0028_auto_20211104_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='tag',
            name='subscriber',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
