# Generated by Django 3.2.7 on 2021-11-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0029_rename_author_assignment_author_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='author_uid',
            new_name='author',
        ),
    ]
