# Generated by Django 3.2.7 on 2021-11-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0028_auto_20211104_1010'),
        ('garnbarn_api', '0029_auto_20211104_0218'),
    ]

    operations = [
    ]
