# Generated by Django 3.2.7 on 2021-11-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0030_merge_0028_auto_20211104_1010_0029_auto_20211104_0218'),
        ('garnbarn_api', '0030_rename_author_uid_assignment_author'),
    ]

    operations = [
    ]
