# Generated by Django 3.2.9 on 2021-11-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0031_merge_20211108_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='secret_key_totp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
