# Generated by Django 3.2.9 on 2021-11-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garnbarn_api', '0032_tag_secret_key_totp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='secret_key_totp',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
