name: Django Test
# Run test on every push or PR
on: [push, pull_request]

jobs:
  Test:
    name: "Run the Test from Django"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: "Mount LINE Secret File"
        run: |
          echo "$LINE_CONFIG" > line-config.json
        shell: bash
        env:
          LINE_CONFIG: ${{secrets.LINE_CONFIG}}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: python manage.py test

  Coverage:
    name: "Submit the coverage data"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: "Mount LINE Secret File"
        run: |
          echo "$LINE_CONFIG" > line-config.json
        shell: bash
        env:
          LINE_CONFIG: ${{secrets.LINE_CONFIG}}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Coverage
        run: coverage run manage.py test
      - name: Submit coverage data to Codecov
        run: bash <(curl -s https://codecov.io/bash)
